CREATE DATABASE Desafio_Roman
GO

USE Desafio_Roman
GO


CREATE TABLE TipoUsuario(
	IdTipoUsuario INT PRIMARY KEY IDENTITY (1,1),
	nomeTipoUsuario VARCHAR (50) NOT NULL UNIQUE,
);
GO

CREATE TABLE EQUIPE (
	IdEquipe INT PRIMARY KEY IDENTITY (1,1),
	nomeEquipe VARCHAR(100) UNIQUE  NOT NULL
);
GO

CREATE TABLE USUARIO (
	IdUsuario INT PRIMARY KEY IDENTITY (1,1),
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario),
	email VARCHAR (255) UNIQUE NOT NULL,
	senha VARCHAR (100) CHECK(len(senha) >= 8) UNIQUE  NOT NULL,
	UserName VARCHAR (100) UNIQUE  NOT NULL
);
GO


CREATE TABLE PROFESSOR (

	IdProfessor INT PRIMARY KEY IDENTITY(1,1),
	idUsuario INT FOREIGN KEY REFERENCES USUARIO (idUsuario),
	IdEquipe INT FOREIGN KEY REFERENCES EQUIPE (idEquipe)

);
GO

CREATE TABLE TEMA (
	IdTema INT PRIMARY KEY IDENTITY(1,1),
	nomeTema VARCHAR (100) UNIQUE NOT NULL,
);
GO

CREATE TABLE PROJETO(

	IdProjeto INT PRIMARY KEY IDENTITY(1,1),
	IdTema INT FOREIGN KEY REFERENCES TEMA(IdTema),
	IdProfessor INT FOREIGN KEY REFERENCES PROFESSOR(IdProfessor),
	nomeProjeto VARCHAR (100) UNIQUE NOT NULL

);
GO
 

 DROP DATABASE Desafio_Roman